import { useState, useEffect } from 'react';
import { getMySalary } from '../../services/salaryService';
import { Loader2, IndianRupee, TrendingDown, Wallet } from 'lucide-react';
import toast from 'react-hot-toast';

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const fmt = (n) => Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2});

const MySalary = () => {
    const [records, setRecords] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(()=>{
        (async()=>{
            try {
                setLoading(true);
                const res = await getMySalary();
                setRecords(res.data.data||[]);
            } catch { toast.error('Failed to load salary history.'); }
            finally { setLoading(false); }
        })();
    },[]);

    if (loading) return (
        <div style={{display:'flex',height:'300px',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:'0.75rem',color:'#16a34a'}}>
            <Loader2 size={40} style={{animation:'spin 1.2s linear infinite'}}/>
            <p style={{color:'#6b7280',margin:0}}>Loading your payslips…</p>
            <style>{`@keyframes spin{100%{transform:rotate(360deg)}}`}</style>
        </div>
    );

    // Latest month for summary card
    const latest = records[0] || null;

    return (
        <div style={{maxWidth:'760px',margin:'0 auto',fontFamily:"'Inter',sans-serif"}}>
            <div style={{marginBottom:'2rem'}}>
                <h1 style={{margin:'0 0 0.35rem 0',fontSize:'1.875rem',fontWeight:'800',color:'#111827'}}>My Salary</h1>
                <p style={{margin:0,color:'#6b7280'}}>Your payslip history generated by the owner.</p>
            </div>

            {/* Latest month card */}
            {latest&&(
                <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'1rem',marginBottom:'1.75rem'}}>
                    {[
                        {icon:<Wallet size={20} color="#16a34a"/>, label:'Base Salary', value:`₹${fmt(latest.base_salary)}`, bg:'#f0fdf4',border:'#bbf7d0',color:'#166534'},
                        {icon:<TrendingDown size={20} color="#dc2626"/>, label:'Deductions', value:`₹${fmt(latest.deductions)}`, bg:'#fef2f2',border:'#fecaca',color:'#991b1b'},
                        {icon:<IndianRupee size={20} color="#1d4ed8"/>, label:`Net — ${MONTHS[latest.month-1]} ${latest.year}`, value:`₹${fmt(latest.net_salary)}`, bg:'#eff6ff',border:'#bfdbfe',color:'#1e40af'},
                    ].map((c,i)=>(
                        <div key={i} style={{backgroundColor:c.bg,border:`1.5px solid ${c.border}`,borderRadius:'12px',padding:'1.25rem'}}>
                            <div style={{display:'flex',alignItems:'center',gap:'0.5rem',marginBottom:'0.5rem'}}>{c.icon}</div>
                            <p style={{margin:'0 0 0.2rem 0',fontSize:'0.72rem',fontWeight:'700',color:c.color,textTransform:'uppercase',letterSpacing:'0.06em'}}>{c.label}</p>
                            <p style={{margin:0,fontSize:'1.4rem',fontWeight:'900',color:c.color}}>{c.value}</p>
                        </div>
                    ))}
                </div>
            )}

            {/* History table */}
            <div style={{backgroundColor:'#fff',borderRadius:'12px',border:'1px solid #e5e7eb',boxShadow:'0 1px 3px rgba(0,0,0,0.06)',overflow:'hidden'}}>
                <div style={{padding:'1rem 1.5rem',backgroundColor:'#f9fafb',borderBottom:'1px solid #e5e7eb'}}>
                    <h3 style={{margin:0,fontWeight:'700',color:'#1f2937',fontSize:'0.95rem'}}>Payslip History</h3>
                </div>
                {records.length===0?(
                    <div style={{padding:'3rem',textAlign:'center',color:'#9ca3af'}}>
                        <IndianRupee size={48} style={{marginBottom:'0.75rem',opacity:0.3}}/>
                        <p style={{margin:0}}>No payslips generated yet. Contact the owner to set up your salary profile.</p>
                    </div>
                ):(
                    <table style={{width:'100%',borderCollapse:'collapse'}}>
                        <thead>
                            <tr>
                                {['Month','Base Salary','Deductions','Net Salary','Notes'].map(h=>(
                                    <th key={h} style={{padding:'0.75rem 1rem',backgroundColor:'#f9fafb',borderBottom:'1px solid #e5e7eb',fontSize:'0.72rem',fontWeight:'700',color:'#6b7280',textTransform:'uppercase',letterSpacing:'0.05em',textAlign:'left'}}>{h}</th>
                                ))}
                            </tr>
                        </thead>
                        <tbody>
                            {records.map(r=>(
                                <tr key={r.record_id}
                                    onMouseOver={e=>e.currentTarget.style.backgroundColor='#fafafa'}
                                    onMouseOut={e=>e.currentTarget.style.backgroundColor='transparent'}>
                                    <td style={{padding:'0.875rem 1rem',borderBottom:'1px solid #f3f4f6',fontWeight:'700',color:'#1f2937'}}>
                                        {MONTHS[r.month-1]} {r.year}
                                    </td>
                                    <td style={{padding:'0.875rem 1rem',borderBottom:'1px solid #f3f4f6',color:'#374151'}}>₹{fmt(r.base_salary)}</td>
                                    <td style={{padding:'0.875rem 1rem',borderBottom:'1px solid #f3f4f6',color:r.deductions>0?'#dc2626':'#6b7280',fontWeight:r.deductions>0?'700':'400'}}>
                                        {r.deductions>0?`- ₹${fmt(r.deductions)}`:'—'}
                                    </td>
                                    <td style={{padding:'0.875rem 1rem',borderBottom:'1px solid #f3f4f6',fontWeight:'800',color:'#166534'}}>₹{fmt(r.net_salary)}</td>
                                    <td style={{padding:'0.875rem 1rem',borderBottom:'1px solid #f3f4f6',color:'#9ca3af',fontSize:'0.82rem'}}>{r.notes||'—'}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                )}
            </div>
        </div>
    );
};

export default MySalary;
